SELECT DISTINCT ISSU.INSTR_ID,ISSU.DENOM_CURR_CDE,ISID.ISID_OID,ISID.MKT_OID
FROM FT_T_ISSU ISSU JOIN FT_T_ISID ISID ON ISID.INSTR_ID=ISSU.INSTR_ID AND ISID.ID_CTXT_TYP= ? 
JOIN FT_T_ISCL ISCL ON ISCL.INSTR_ID=ISSU.INSTR_ID AND  ISCL.INDUS_CL_SET_ID='BBMKTSCT'
WHERE   ISID.ISS_ID= ?  AND ISCL.CL_VALUE= ? 